[Greeter]
background=/usr/share/backgrounds/senos/default.png
draw-user-backgrounds=false
theme-name=Mint-Y
icon-theme-name=Tela-circle-light
cursor-theme-name=Bibata-Modern-Classic
font-name=Be Vietnam Pro 11
